config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do
  resources :projects do
    get 'report'      => 'report#index'
    get 'report/list' => 'report#list'
  end
end

app/controllers/report_controller.rb
class ReportController < ApplicationController
  unloadable
  before_filter :find_project, :authorize, :only => :index

  # プラグインのトップページ
  def index
    #メール用データの作成(途中)
    @mail_text = ""
    @target_users.each do |user|
       str = ""
#      str = user.to_s + "%0D%0A"
      str = user.to_s.encode("Shift_JIS") + "%0D%0A"
      
      @target_projects.each do |project|
        project.issues.each do |issue|

#          str << project.to_s + "%0D%0A"

     #          if user == issue.assigned_to && issue.status.id != 5 && issue.status.id != 6 && issue.start_date < Time.now + 30.days then
     #       #   if is_disp_issue(user, issue) && issue.parent_id.blank?
     #            str << issue.id + " : " + issue.subject + "%0D%0A"
     ##            str << "%20%20#" + issue.id.to_s + " : " + issue.subject + " (" + issue.start_date.strftime("%m/%d").to_s + "-" + issue.due_date.strftime("%m/%d").to_s  + ") ["+ issue.status.name + "]" + "%0D%0A"
     #            str << "%20%20#" + issue.id.to_s + " : " + " (" + issue.start_date.strftime("%m/%d").to_s + "-" + issue.due_date.strftime("%m/%d").to_s  + ") ["+ issue.status.name + "]" + "%0D%0A"
     #            issue.journals.each do |j|
     #              if j.created_on > Time.now - 7.days && j.notes.present? then # 1週間のコメント
     #  #            str << j.created_on.to_s.split[0] + " " + j.notes.delete("<").delete(">") + "\n"
     ##                str << "%20%20%20%20" + j.created_on.strftime("[%m/%d]") + "%0D%0A%20%20%20%20" + j.notes.delete("<").delete(">").to_s.gsub(/(\r\n|\r|\n)/, "%0D%0A%20%20%20%20") + "%0D%0A"
     #              end
     #            end # issue.journals.each.do
     #          end # if user == issue.assigned_to
        end # @project.issues.each do
      end
         #      @mail_text << str.encode("Shift_JIS")
         #      @mail_text << str.encode("UTF-8")
        @mail_text << str
    end #@target_users.each do
      @mail_title = "Project Weekly Report"
  end

  private
  # プロジェクトの選択
  def find_project
    @all_projects = Project.all
    @project = Project.find(params[:project_id])
    @project_id = @project.id
    @target_projects = []
    @target_users = []
    @users = []
    
    @all_projects.each do |prj|
      if (prj.id == @project_id || prj.parent_id == @project_id) && prj.status != 5
        @target_projects << prj
        prj.users.each do |user|
          @target_users << user
          @users << user
        end
      end
    end
    
    @target_users.uniq!
    @target_users.sort!

  rescue ActiveRecord::RecordNotFound
    render_404
  end
end

app/helpers/report_helper.rb
# -*- encoding: UTF-8 -*-
module ReportHelper
  def period
   start_date = Time.now - 10.days
   end_date = Time.now + 10.days
   
   start_date.strftime("%Y/%m/%d") + " - " + end_date.strftime("%Y/%m/%d")
  end
  
  def is_disp_user(user, target_projects)
    target_projects.each do |project|
      project.issues.each do |issue|
        if is_disp_issue(user, issue)
          return true
        end
      end
    end
    return false
  end

  def is_disp_project(project, current_project)
    project.id == current_project || project.parent_id == current_project
  end

  def is_disp_issue(user, issue)
    user.name == issue.assigned_to.to_s && issue.status.id != 5 && issue.status.id != 6 && issue.start_date < Time.now + 10.days
  end
  
  def is_parent(user, issue, project)
    #孫までは対応
    project.issues.each do |sub_issue|
      if issue.id == sub_issue.parent_id && is_disp_issue(user, sub_issue)
        return true
      end
      
      if issue.id == sub_issue.parent_id
        project.issues.each do |sub_sub_issue|
          if sub_issue.id == sub_sub_issue.parent_id && is_disp_issue(user, sub_sub_issue)
            return true
          end
        end
      end
    end
    return false
  end
  
  def is_disp_journal journal
    journal.notes.present? && journal.created_on > Time.now - 10.days #journalが存在し、直近10日間に更新されたもの
  end
  
  def issues_sorted(issues)
    sorted = issues.sort{|aa, bb| 
      aa.due_date <=> bb.due_date
    }
#         prj.issues = array
##         prj.issues.clear
#         prj.issues << array
#         prj.issues.slice!(0,array.size)
    return sorted
  end
  
  def status_word status
#    if status.id == 1
#      "未"
#    elsif status.id == 2
#      "中"
#    elsif status.id == 3
#      "済"
#    elsif status.id == 4
#      "済"
#    elsif status.id == 5
#      "済"
#    elsif status.id == 6
#      "済"
#    end
  end
  
  def start_date_color(issue)
    if issue.status.id == 1 && issue.start_date < Time.now #Newで開始日が過ぎている
      "red"
    else
      "black"
    end
  end
  
  def due_date_color(issue)
    if issue.status.id == 2 && issue.due_date < Time.now #In Progressで終了日が過ぎている
      "red"
    else
      "black"
    end
  end
end

app/views/report/index.html.erb
<% def disp_issues_tree(user, project, parent_id, count) %>
  <% return if count > 5 %>
    <ul>
      <% issues_sorted(project.issues).each do |issue| %>
        <% if (is_disp_issue(user, issue) || is_parent(user, issue, project)) && ((count == 1 && issue.parent_id.blank?) || (count > 1 && issue.parent_id == parent_id)) %>
          <li>
              <%= link_to ("#" + issue.id.to_s + " : " + issue.subject), issue_path(issue.id) %>
              [<%= issue.custom_field_values[1] %>]
              (<font color="<%= start_date_color(issue) %>"><%= issue.start_date.strftime("%m/%d") %></font> - 
               <font color="<%= due_date_color(issue) %>"><%= issue.due_date.strftime("%m/%d") %></font>)
              [<%= issue.status %>]
        <% if user.name == issue.assigned_to.to_s %>
            <ul>
              <% issue.journals.each do |journal| %>
                <% if is_disp_journal journal %>
                  <li>
                    <div style="font-size:100%; padding: 0.5em 1em; margin: 1em 0; color: #2c2c2f; background: whitesmoke; border: solid 1px #DDDDDD; border-radius: 6px;">
                      <%= simple_format(journal.created_on.strftime("[%m/%d]") + "\n" + journal.notes.delete("<").delete(">").to_s) %>
                    </div>
                  </li>
                <% end %>
              <% end %>
            </ul>
        <% end %>
            <% disp_issues_tree(user, project, issue.id, count + 1) %>
          </li>
        <% end %>
      <% end %>
    </ul>
<% end %>


<% @target_users.each do |user| %>
  <% if is_disp_user(user, @target_projects) %>
    <hr><h2><%= link_to user, user_path(user.id) %></h2>
  <% end %>
  <% @target_projects.each do |project| %>
    <% if is_disp_project(project, @project_id) %>
    <ul>
      <% project.issues.each do |issue| %>
        <% if is_disp_issue(user, issue) %>
          <li><h4><%= link_to project.name, project_path(project) %></h4></li>
          <% break %>
        <% end %>
      <% end %>
      <% disp_issues_tree(user, project, 0, 1) %>
    </ul>
    <% end %>
  <% end %>
<% end %>